2022-04-04T14:02:19.360+0900    WARN    user/handler.go:16      Code: database_error, Msg: failed to get user   {"Stack": "failed to get user\ntrial-go-stacktrace/internal/errors.Errorf\n\t/Users/yuichi_kadota/go/src/github.com/Yuichi-Kadota/trial-go-stacktrace-log/internal/errors/errors.go:29\ntrial-go-stacktrace/repository/user.UserImpl.GetUser\n\t/Users/yuichi_kadota/go/src/github.com/Yuichi-Kadota/trial-go-stacktrace-log/repository/user/impl.go:11\ntrial-go-stacktrace/services/user.get\n\t/Users/yuichi_kadota/go/src/github.com/Yuichi-Kadota/trial-go-stacktrace-log/services/user/service.go:7\ntrial-go-stacktrace/services/user.GetHandler.func1\n\t/Users/yuichi_kadota/go/src/github.com/Yuichi-Kadota/trial-go-stacktrace-log/services/user/handler.go:13\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/yuichi_kadota/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/Users/yuichi_kadota/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/yuichi_kadota/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/Users/yuichi_kadota/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/Users/yuichi_kadota/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/Users/yuichi_kadota/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/Users/yuichi_kadota/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/usr/local/Cellar/go/1.17/libexec/src/net/http/server.go:1929\nruntime.goexit\n\t/usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581\n"}